title:               DWN's DIGITAL
include:             ['_pages']
exclude:             ['_includes/notes_graph.json']
# You may need to change the base URL depending on your deploy configuration.
# Specifically, when using GitHub Pages, the baseurl should point to where GitHub
# Pages deploys your repository (which is usually the repository name).
# baseurl:             'https://swolrus.github.io'
baseurl:                ''
# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set "his to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: true

#permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at

sass:
  sass_dir:  _sass
  style:  :compressed

collections:
  notes:
    output: true
    permalink: /note/:path/

kramdown:
  syntax_highlighter: rouge
  math_engine: katex
  syntax_highlighter_opts:
    block:
      line_numbers: true

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"


      ## Built-in Variables

      ## In addition to the variables provided in the configuration file, there are built-in variables that can be used in the scope comparison.

      ## | Variable | Description |
      ## | --- | --- |
      ## | `page.regularPath` | The path of the page relative to the `content` directory, with the extension removed. This is equal to the `page.path` without the `page.ext` |
      ## | `page.directory` | The directory portion of the `page.path` |
      ## | `page.base` | The basename of the `page.path` |
      ## | `page.stem` | The stem of the `page.path` (the filename without the extension) |
      ## | `page.ext` | The file extension of the `page.path` |

      ## Examples

      ### Basic

      ## This example shows how to set a default layout for all files in `content/notes` and `content/articles` directories.
